# CMake generated Testfile for 
# Source directory: D:/Laba_ppc/ppc-2024-autumn/tasks
# Build directory: D:/Laba_ppc/ppc_build/tasks
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mpi_func_tests]=] "D:/Laba_ppc/ppc_build/bin/mpi_func_tests.exe")
  set_tests_properties([=[mpi_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mpi_func_tests]=] "D:/Laba_ppc/ppc_build/bin/mpi_func_tests.exe")
  set_tests_properties([=[mpi_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mpi_func_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/mpi_func_tests.exe")
  set_tests_properties([=[mpi_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mpi_func_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/mpi_func_tests.exe")
  set_tests_properties([=[mpi_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[mpi_func_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mpi_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/mpi_perf_tests.exe")
  set_tests_properties([=[mpi_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mpi_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/mpi_perf_tests.exe")
  set_tests_properties([=[mpi_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mpi_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/mpi_perf_tests.exe")
  set_tests_properties([=[mpi_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mpi_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/mpi_perf_tests.exe")
  set_tests_properties([=[mpi_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[mpi_perf_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[omp_func_tests]=] "D:/Laba_ppc/ppc_build/bin/omp_func_tests.exe")
  set_tests_properties([=[omp_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[omp_func_tests]=] "D:/Laba_ppc/ppc_build/bin/omp_func_tests.exe")
  set_tests_properties([=[omp_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[omp_func_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/omp_func_tests.exe")
  set_tests_properties([=[omp_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[omp_func_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/omp_func_tests.exe")
  set_tests_properties([=[omp_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[omp_func_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[omp_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/omp_perf_tests.exe")
  set_tests_properties([=[omp_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[omp_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/omp_perf_tests.exe")
  set_tests_properties([=[omp_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[omp_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/omp_perf_tests.exe")
  set_tests_properties([=[omp_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[omp_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/omp_perf_tests.exe")
  set_tests_properties([=[omp_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[omp_perf_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[seq_func_tests]=] "D:/Laba_ppc/ppc_build/bin/seq_func_tests.exe")
  set_tests_properties([=[seq_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[seq_func_tests]=] "D:/Laba_ppc/ppc_build/bin/seq_func_tests.exe")
  set_tests_properties([=[seq_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[seq_func_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/seq_func_tests.exe")
  set_tests_properties([=[seq_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[seq_func_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/seq_func_tests.exe")
  set_tests_properties([=[seq_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[seq_func_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[seq_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/seq_perf_tests.exe")
  set_tests_properties([=[seq_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[seq_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/seq_perf_tests.exe")
  set_tests_properties([=[seq_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[seq_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/seq_perf_tests.exe")
  set_tests_properties([=[seq_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[seq_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/seq_perf_tests.exe")
  set_tests_properties([=[seq_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[seq_perf_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[stl_func_tests]=] "D:/Laba_ppc/ppc_build/bin/stl_func_tests.exe")
  set_tests_properties([=[stl_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[stl_func_tests]=] "D:/Laba_ppc/ppc_build/bin/stl_func_tests.exe")
  set_tests_properties([=[stl_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[stl_func_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/stl_func_tests.exe")
  set_tests_properties([=[stl_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[stl_func_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/stl_func_tests.exe")
  set_tests_properties([=[stl_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[stl_func_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[stl_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/stl_perf_tests.exe")
  set_tests_properties([=[stl_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[stl_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/stl_perf_tests.exe")
  set_tests_properties([=[stl_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[stl_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/stl_perf_tests.exe")
  set_tests_properties([=[stl_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[stl_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/stl_perf_tests.exe")
  set_tests_properties([=[stl_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[stl_perf_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tbb_func_tests]=] "D:/Laba_ppc/ppc_build/bin/tbb_func_tests.exe")
  set_tests_properties([=[tbb_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tbb_func_tests]=] "D:/Laba_ppc/ppc_build/bin/tbb_func_tests.exe")
  set_tests_properties([=[tbb_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tbb_func_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/tbb_func_tests.exe")
  set_tests_properties([=[tbb_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tbb_func_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/tbb_func_tests.exe")
  set_tests_properties([=[tbb_func_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[tbb_func_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[tbb_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/tbb_perf_tests.exe")
  set_tests_properties([=[tbb_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[tbb_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/tbb_perf_tests.exe")
  set_tests_properties([=[tbb_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[tbb_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/MinSizeRel/tbb_perf_tests.exe")
  set_tests_properties([=[tbb_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[tbb_perf_tests]=] "D:/Laba_ppc/ppc_build/bin/RelWithDebInfo/tbb_perf_tests.exe")
  set_tests_properties([=[tbb_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;115;add_test;D:/Laba_ppc/ppc-2024-autumn/tasks/CMakeLists.txt;0;")
else()
  add_test([=[tbb_perf_tests]=] NOT_AVAILABLE)
endif()
